adjtomo/pysep

README.md
pysep/pysep.py
pysep/utils/fmt.py

This PR introduces the ability to use the legacy filename schema from the old version of PySEP, since the new naming schema may cause errors with workflows established using the old version of PySEP. 
Under the new schema, event tags are named after the origin time (as opposed to origin time + Flinn Engdahl region), and output SAC files are saved directly to the output directory (as opposed to the SAC/ directory). SAC file naming schema also changed to honor the legacy version, consisting of the new event tag concatenated with trace ids ending with a lower case component letter (e.g., BH.r, as opposed to BHR.sac).
It also allows the user to manually set the event tag (which controls output directory name and SAC file names), and the names of all the output files except for the SAC files …

Legacy naming schema

---

README.md
pysep/pysep.py
pysep/recsec.py

Bug fix for PySEP ignoring automatic file naming for config files that it has already generated. 
1) Changed 'event_tag' overwrite parameter to 'overwrite_event_tag' so as to not confuse the actual attribute
2) Made 'legacy_naming' attribute hidden so that it doesnt get written to the config file and overwrite the users decision to use legacy naming.
3) recsec can now recognize legacy filenames for SAC files, whereas before it would have failed to locate them because they are not suffixed with '.sac'
4) updated readme to reflect change in 'overwrite_event_tag' parameter

Bug fix legacy naming

---

README.md
pysep/pysep.py
pysep/recsec.py
pysep/tests/test_utils.py
pysep/utils/cap_sac.py
pysep/utils/fmt.py

This PR fixes some issues with writing the output SAC waveform files
- Bug fixes SAC thinking the trace start time was the event origin time (spoiler alert: it's not) by setting IZTYPE, E and B as SAC header attributes, which tell ObsPy to consider trace start as a reference time, not origin time
- KEVNM (event name) was being truncated weirdly because SAC only allows 16 characters for thsi field. KEVNM is now always set as the legacy-style event tag, which is a 16 character tag generated from the event origin time (up to milliseconds)
- Allow user to ignore appending TauP picks to the SAC header by setting `taup_model`==None
- Added tests to cover origin times and the legacy file naming introduced in #22 
Misc changes:
- Event tags can now be overwritten by user, otherwise they have …

Bugfix sac errors

---

pysep/configs/alvizuri_tape_2018/2006-10-09T013528_NORTH_KOREA.yaml
pysep/configs/denali_nodal/2019-02-25T182230_CANTWELL_NODAL.yaml
pysep/configs/denali_nodal/2019-02-25T182230_CANTWELL_NONNODAL.yaml
pysep/configs/misc_events/1988-02-15T181000_KERNVILLE_EXPLOSION.yaml
pysep/configs/misc_events/2016-01-24T103037_INISKIN.yaml
pysep/configs/mtuq_workshop_2022/2009-04-07T201255_ANCHORAGE.yaml
pysep/configs/mtuq_workshop_2022/2014-08-25T161903_ICELAND.yaml
pysep/configs/mtuq_workshop_2022/2017-09-03T033001_NORTH_KOREA.yaml
pysep/configs/mtuq_workshop_2022/2020-04-04T015318_SOUTHERN_CALIFORNIA.yaml
pysep/configs/scec/2002-03-16T213324_SOUTHERN_CALIFORNIA.yaml
pysep/configs/tape_etal_2018/2012-04-11T092157_TAPE_2018.yaml
pysep/configs/template_config.yaml
pysep/pysep.py
pysep/tests/test_utils.py
pysep/utils/process.py

re-introduces default pre-filtering option that was present in old PySEP, which calculates pre-filter corners and applies pre-filtering during instrument response removal based on waveform length and trace sampling rate.
This is made the default behavior of the pre-filter option, all default config files are now updated with this 'default' behavior if their prefilt option was set as None. Adds in a test to check the pre-filter estimation function.

add feature pre-filtering

---

pysep/recsec.py
pysep/tests/test_recsec.py

Adds in zero padding for the RECord SECtion tool, which allows the User to pad zeros at the start and end of a trace. This occurs after detrending/tapering, but before filtering, which is meant to accommodate a continuous waveform (as opposed to having a jump from zero to some nonzero amplitude).
Also adds in a pytest test suite for the record section plotter. These tests are simple, they just test all the options by running RecSec with a variety of input parameters to make sure code executes but there are no checks for image creation. Probably okay for the current scale of RecSec, but if it becomes a larger tool we may need to rethink how to structure its tests

Feature zeropad

---

pysep/pysep.py
pysep/recsec.py
pysep/tests/test_process.py
pysep/tests/test_pysep.py
pysep/utils/cap_sac.py
pysep/utils/process.py

This PR fixes a rotation bug pointed out by @ammcpherson, who noticed RTZ rotated streams in the current PySEP version did not match those from the legacy codebase. 
This is related to an ObsPy bug (https://github.com/obspy/obspy/issues/2623) which causes the Stream().rotate() function to use the FIRST backazimuth (BAz) value to rotate all traces in a stream even if they don't share this BAz value. This cased rotation to essentially fail silently.
As a bugfix, during NE->RT rotation, we rotate station by station, which provides the correct BAz value for each rotation. 
Also, fixes a RecSec bug where zero padding and setting x limits together was leading to an incorrectly defined time axis.

Bugfix rotation

---

.github/workflows/dispatch-container.yml

This is the workflow to trigger the container build workflow at https://github.com/SeisSCOPED/pysep/blob/main/.github/workflows/docker-publish.yml 
Note that an admin of this repo will need to add a PAT and name it as `PAT_TOKEN` in this repository's secret to make it work. We also need to grant this admin write access to the pysep container repo.

add workflow to trigger container build

---

README.md
pysep/pysep.py
pysep/recsec.py
pysep/utils/io.py

This PR introduces the feature to plot record sections from SPECFEM2D synthetics.
This was not possible before as RecSec did not have the ability to read SPECFEM2D SOURCE files.
Nor did it have the capability to handle Cartesian domains (only geographic). Which was also a boon for SPECFEM3D_Cartesian domains.
RecSec can how handle both of these features and creates a barebones SAC header that is only used to complete the record section. Tested with some 2D synthetics generated using the SeisFlows Example 2 workflow.

Feature sem2d recsec

---

README.md
pysep/recsec.py

This PR introduces the ability to plot two sets of synthetics together in a record section, whereas previously the `--pysep_path` flag HAD to be ObsPy-readable waveform data. Now with the `--synsyn` flag, RecSec knows that both the `--pysep_path` and `--syn_path` directories contain synthetic waveforms and will handle them appropriately.

Feature syn syn

---

README.md
pysep/recsec.py
pysep/utils/plot.py

Addressing Issue #50 
- Adds in geometric spreading as a 'scale_by' option for RecSec
- Allows user to set parameters and exclude stations from geometric spreading equation
- Creates a scatter plot to show geometric spreading, following example shown in original post of #50 
>__NOTE__: Stations with poor data must be removed manually, otherwise they will throw off the scaling in the record section. This might be addressed in a future PR but at the moment since these data shouldn't be considered anyway, I think leaving it up to the User to remove them is sufficient
See e.g., below figures, which were generated using
```bash
$ pysep -p mtuq_workshop_2022 -e 2009-04-07T201255_ANCHORAGE.yaml
$ cd 2009-04-07T201255_ANCHORAGE
$ rm -r SAC/*RC01* SAC/*ALPI* SAC/*SPBG*  # getting rid of bad …
```

RecSec feature geometric spreading

---

README.md
pysep/recsec.py
pysep/utils/plot.py

Makes some changes to update the default look of record section and geometric spreading figures based on comments from @carltape and @ytian159. Changes are as follows:
- RecSec title reformatting, dropped unnecessary information, added hypocenter information. Some information (move out, filtering) is simply not shown if not used, and geometric spreading scaling shows `k` and `f` values
- Y label format (y_fmt) which was previously in the title has now been moved to plot itself and follows the location of the y-axis labels. 
- Geometric spreading figure id can now be set with parameter `geometric_spreading_save` (updated readme to show this)
- Geometric spreading figure now scales appropriately to the max x and y values of the scatter plot
- Geometric spreading figure now plots the x-axis …

Improve recsec aesthetics

---

pysep/configs/test/test_config_rotate_bug.yaml
pysep/pysep.py
pysep/tests/test_process.py
pysep/tests/test_utils.py
pysep/utils/curtail.py

Related to #35, this PR fixes a bug in which missing rotation metadata (which comes from the datacenter) throws a TypeError during the ObsPy rotate command. 
Occasionally Station metadata (contained in the inventory) has NoneType set for the azimuth or dip of a given channel. Prior to this bugfix, this made its way into the obspy.signal.rotate2zne() function, which attempted to run a NoneType through a degrees to radian converter, causing a TypeError.
This bugfix PR addresses this by:
1) explicitly checking dip and azimuth values for each station in the Inventory. If any return NoneType, then PySEP will kick out the entire station to avoid an issue. 
2) the rotate function now addresses each grouping of channels individually (e.g., BHZ, BHE, BHN), whereas before all channels were …

Bugfix missing rotation metadata throwing TypeError

---

environment.yml
pyproject.toml
pysep/pysep.py
setup.py

- Removes `llnl_db_client` as a hard dependency from python and conda install files to simplify install procedures 
- Hides `llnl_db_client` top level import behind a try-except block and has a check during init to see if LLNL is required
- Moves `llnl_db_client` to an optional install dependency which can be accessed via pip
- Adds in a legacy 'setup.py' file incase this is required by any future systems
- Tests still pass and tested install procedure and attempting to use LLNL client when not installed. All worked as expected

Remove llnl_db_client hard dependency

---

pysep/pysep.py
pysep/recsec.py
pysep/utils/cap_sac.py
pysep/utils/curtail.py
pysep/utils/process.py

- Add missing parameters to PySEP docstring
- Rewrite PySEP docstring parameter definitions for those that were lacking
- Categorize PySEP docstring parameters to make things easier to read
- Fixes some flag parameters not actually being used during PySEP processing
- Removes hard restriction of requiring event depth and magnitude when default event selection used
- Categorize RecSec dosctring to make things easier to read
- Removes unneeded function from RecSec script

clean up docstrings of pysep/recsec, bugfix pysep restrictions

---

pysep/pysep.py
pysep/recsec.py
pysep/utils/cap_sac.py
pysep/utils/fetch.py

- Address Issue: #71 
- Fixes bug in PySEP where parameters `event_depth_km` and `event_magnitude` were not being allowed because something in the intermediate processing steps would break
- Parts of the code that a required 'evdp' (event depth) in the SAC header included, which broke with NoneType depth:
- Fetching TauP arrivals
- SAC headers
- record section titles
- Event magnitude required in:
-  SAC headers
- 'search' type event selection
- record section titles
- The above functions now skip over depth or magnitude information when these are set as NoneType, or allow them through as NoneTypes

Bugfix: unable to set event_depth_km or event_magnitude as NoneType

---

pysep/pysep.py
pysep/recsec.py

Addresses Issue #70
Adds feature `tmarks` which allows for setting vertical lines at certain time values. These lines do **not** take time shift or move out into account, they simple plot lines at reference times. It can be implemented via recsec on the command line
```bash
recsec --tmarks 0 100 200
```
or via scripting:
```python
RecordSection(tmarks=[0, 100, 200]...)  # units: seconds
```
Keyword arguments can be used to control the look of the tmark lines. Check function `recsec.RecordSection._plot_tmarks()` for available keyword arguments.

Feature recsec tmarks

---

pysep/pysep.py
pysep/tests/test_process.py
pysep/tests/test_utils.py
pysep/utils/process.py

Addresses Issues #83 and #67 dealing with gappy data and waveform start and end times.
In current version of PySEP, gapped data is not handled, any data with gaps is thrown own during preprocessing.
Additionally, waveforms are gathered from data centers directly on the requested bounds (+/- s around origin time), which may cause saved data to be shorter than expected due to time series being slightly truncated during rotation, resampling or other preprocessing steps.
This PR addresses these issues by:
- Introduce parameters `fill_data_gaps` and `gap_fraction` to address data gaps
- By default `fill_data_gaps` is False, which handles gapped data like the current code, by removing stations with gaps
- `fill_data_gaps` can also be a series of values which tell PySEP to keep gapped data, and …

Feature: fill data gaps and bug fix trim start end times

---

CHANGELOG.md
pysep/pysep.py
pysep/tests/test_process.py
pysep/utils/curtail.py
pysep/utils/process.py

Related to #67 and #83 
Stations with data gaps at the beginning of end of a trace (that is there is no data at the requested starttime or at the requested endtime) was being removed because ObsPy's Trace.merge() feature (which was being used to fill data gaps), does not address these boundary times.
To retain these stations, the trim (https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.trim.html) function now fills data gaps of these boundary times.
Changelog:
- Forces `seconds_*_ref`, `seconds_*_event` to be of type float in the Pysep.check() function. Before they were allowed to set as integer which caused floating point rounding errors and trace length inconsistency
- During the trim operation (cutting start and end time), allow User to fill data gaps at the boundaries of …

Bugfix: stations removed insufficient time 

---

pysep/recsec.py

Address #75 fixing sorting order and multi-page record sections. This PR is submitted prematurely in the interest of saving some time, and does not address all topics
Changelog:
1. reverse sort order for `abs_distance` and `abs_distance_r`. `abs_distance` now has smallest distance at the top of figure
2. reverse sort order for `abs_azimuth` and `abs_azimuth_r`. `abs_azimuth` now has smallest azimuth at the top of figure
3. bugfix: y-label locations for absolute sorting not showing properly, they now show outside the right-side border of the record section
4. fix multi-page sort order for `abs_distance` and `abs_distance_r` record sections. the order of pages outputted by multi-page sorting starts at the top of the equivalent single-page record section
6. fix multi-page sort order for …

Bugfix: plotw_rs sort order and multi-page order

---

pysep/utils/plot.py

Related to #82 
Previous source receiver map was very simple and not well adapted to global scales. It also did not center plots on the hypocenter of the event causing issues when the event was not located within the domain.
Changelog:
- Catalog is plotted first, which centers figure around event hypocenter (except for global figures)
- Logic check now selects between 'local' (<5000km), 'ortho' (<10000km) and 'global' projections based on the maximum source-receiver distance
- Allow subsetting stations in the inventory based on trace ids
```python
subset = [tr.get_id() for tr in st][:100]
plot_source_receiver_map(inv=inv, event=event, subset=subset)
```
Two examples to show different plotting scales:

improve source receiver map plotting

---

README.md
pysep/pysep.py
pysep/recsec.py
pysep/tests/test_utils.py
pysep/utils/cap_sac.py
pysep/utils/fetch.py

Related to #92 
PySEP can append TauP theoretical arrival times to SAC headers, but the previous implementation was too rigid and failed for large source-receiver distances (>100*) because it was only allowing in phases 'P' and 'S'.
This PR fixes this system and also introduces a RecSec feature for applying per-trace time shifts based on phase arrivals.
- Removes hardcode phase list when NoneType passed in for TauP arrival times, now defaults to collecting all phases ('ttall') unless user specifies a phase list
- Merged functions `get_taup_arrival_w_sac_headers` and `get_taup_arrivals`, the new `get_taup_arrivals` can get arrival times with either SAC headers or event and inv objects (reduces code redundancy, no API change)
- Made some adjustments to SAC header input values due to hard …

improve TauP theoretical arrival usage

---

docs/conf.py
pyproject.toml
pysep/__init__.py
pysep/pysep.py
pysep/utils/plot.py

Not a very coherent theme to these changes, just addressing a few open issues in one go:
- Change parameter default for `remove_clipped` from False -> True (https://github.com/adjtomo/pysep/issues/80#issuecomment-1455243240)
- Bugfix: PySEP `load` was not retaining keyword arguments from a YAML parameter file
- Added version number to package so Users can import version number in Python (#95)
- Display PySEP version number in the debug log messages (#95)
- Map plotting: local scale plots now auto-scale like the ObsPy version of the plot function. Previously local scale figures would have event or stations out of map bounds, or have strange scales if stations were very linear in their arrangement.

General updates and bugfixes

---

pysep/recsec.py

Address #99 and https://github.com/adjtomo/pysep/issues/75#issuecomment-1458960563
RecSec absolute sorting was implemented incorrectly because to get smaller values on top, the y-axis was inverted, but this also flipped the waveforms, causing polarity flips on otherwise normal seismograms.
Changelog:
- Bugfix: When sorting by absolute, which inverts the y-axis, applies a sign flip to waveform data to show correct waveform polarity #99 
- Feature: Added automatic y-tick scaling for absolute sorting as it was hardcoded to small values previously, which caused too-dense tick marks for very large distance ranges
- Bugfix: Allow `abs_backazimuth` and `abs_backazimuth_r` as valid sorting options, which were not listed as acceptable values previously. …

Bugfix: RecSec abs sorting and y-tick scaling

---

docs/pysep.rst
pysep/pysep.py
pysep/recsec.py
pysep/utils/io.py

Related to #75, #77
Internal rewriting of PySEP's file writing system to be more flexible and useful. Also minor typo fixes and bugfixes piggybacking
- Changed default files that are written out by PySEP ("inv,event,stream,sac,config_file,station_list")
- No longer write out ``weights*.dat`` files by default, User must request using ``write_files``='all' or ``write_files``='weights_dist'
- Files are written out **when available** and not at the end of the workflow  #77 
- Log file (same as is printed to stdout) is written out as ``pysep.log`` #77 
- Turn off azimuth bins when sorting by absolute (back)azimuth  #75 
- Output stations file: `stations_file.txt` -> `station_file.txt`
- Allow User to bypass ``event_tag`` subdirectory  #77
- Allow User to bypass ``SAC`` waveform subdirectory …

overhaul file writing system plus general updates

---

CHANGELOG.md
docs/conf.py
docs/how_to_version_release.md
pyproject.toml
pysep/__init__.py
pysep/recsec.py
pysep/utils/curtail.py
pysep/utils/process.py

- #117: New quality control function that removes Traces with array length <= 1, which would cause preprocessing to fail
- #116: RecSec now logs absmax amplitudes and absmax amplitude ratios IFF both `st` and `st_syn` are provided
- #120: Version number is now only sourced from `pyproject.toml`, other locations now reference this file to determine version number
- Bumps version number to 0.5.0 for the latest `Devel` branch

General Improvements: improve recsec log, single-source version, bugfix zero trace length

---

pysep/recsec.py

The RecordSection parameter `xlim_s`, when used in conjunction with the 'scale_by' == `normalize` would identify the section of waveform to check max amplitudes, with which it would normalize the remainder of the trace. 
Previously it was selecting sections of the waveform using the time value from `xlim_s`, rather than the index value required (time * sampling rate), which caused the incorrect section of waveform to be used for trace normalization. 
This PR fixes this bug by converting the time values in `xlim_s` to index values for selecting max amplitudes fro trace normalization

Bugfix: incorrect RecSec xlim_s indexing

---

pysep/recsec.py
pysep/utils/io.py

This PR adds some features to improve integration of PySEP with the other adjTomo tools (SeisFlows and Pyatoa).
1) RecSec ability to plot misfit windows as rectangles over record sections, windows must be input as a dictionary of list of tuples where the keys are trace IDs and the tuple values are start and end time of the windows, in seconds, e.g.,
```python
{"NN.SSS.LL.CCC": (0, 100)}
```
2) Ability to read streams and windows from ASDFDataSets so that they may be plotted with RecSec. These datasets are the outputs of SeisFlows + Pyaflowa inversions and contain additional Pyatoa auxiliary data that is required for plotting.

adds ability to plot misfit windows and read ASDFDataSets

---

pysep/recsec.py
pysep/tests/test_recsec.py

Small RecSec PR to address #131 concerning zero amplitude traces. Previously, zero amplitude normalization would cause the NumPy trace arrays to become NaNs which would not plot, but would allow RecSec to continue running. There are now some guardrails in place to prevent these arrays from becoming NaNs.
- If RecSec tries to normalize by 0, throws a warning and normalizes by 1 instead. May have unintentional consequences, but allows waveforms to be plotted
- Feature: user can now set RecSec kwargs for `obs_color` and `syn_color` to change the color of observed and synthetic waveforms, previously these were hardcoded to black and red, respectively.
- Adds Test to cover this case, not a great test but it atleast runs the case where amplitudes are 0, and will require a visual check to ensure …

Bugfix RecSec ZeroDivisionError on trace normalization

---

pysep/tests/test_utils.py
pysep/utils/cap_sac.py

Related to #132, original SAC header functions for SPECFEM synthetics were very barebones, just providing enough information for RecSec to take over and plot. However it is beneficial to include all available SAC headers since the code was already written for normal data.
- `append_sac_headers_cartesian` now includes all SAC header values found in `append_sac_headers` except for `cmpinc` and `cmpaz` which are component based inclination and azimuth and not really necessary for synthetics
- Added some improved log warnings for normal SAC header to warn User when optional parameters like `evdp` were not appended, previously these passed through silently
- Improved tests to catch new functionalities

Improve SAC header append functions

---

CHANGELOG.md
docs/README.md
pyproject.toml
pysep/recsec.py
pysep/tests/test_utils.py
pysep/utils/cap_sac.py
pysep/utils/io.py

- Hotfix: incorrect sorting in CAP weights file related to #144
A few small riders 
- Change log level from warning -> info for empty origin time when reading SPECFEM sources
- Remove README doc page about publishing to PyPi, moved this to adjDocs
- Added some more to the RecSec docstring

Hotfix: CAP weight file sorting

---

pysep/recsec.py
pysep/tests/test_recsec.py

Small features that 1) allow exporting processed waveforms from RecordSection so that these waveforms can be used in other plotting tools or further analysis, and 2) ignoring location codes when matching data to synthetics when creating RecordSections
- New RecordSection command line argument `--export_traces` or class argument `export_traces` can be used interchangeably to trigger trace export 
- `export_traces` boolean flag triggers export of both `st` and `st_syn` (if available) as SAC files 
- Files are exported in the same directory they were read from, with appended suffixes (`_st_proc` and `_syn_proc` for data and synthetics, respectively), separated by component
- New command line argument `--remove_locations` or class argument `remove_locations` to not take location code into …

RecordSection allow export traces and ignore locations

---

pysep/pysep.py
pysep/tests/test_declust.py
pysep/tests/test_recsec.py
pysep/tests/test_utils.py
pysep/utils/cap_sac.py
pysep/utils/fetch.py

Related to SAC header time incorrectly saving and causing incorrect NZ time values in SAC header. See #152 for more information. Fixes this by forcibly truncating the `microsecond` attribute of the events `UTCDateTime` object to force it into 3 digit millseconds. Although SAC header says these should be allowable as integers, we'll just be safe and truncate. I threw in one or two random formatting fixes I found rooting around.

Bugfix SAC header NZMSEC overflow causing incorrect SAC header origin time

---

docs/recsec.rst
pysep/recsec.py
pysep/tests/test_recsec.py

Relevant Issues: #119, #163, #159
- New RecSec  parameter `time_shift_s_syn` which mimics `time_shift_s` allowing the user to time shift their data. `time_shift_s_syn` is optional and allows users to time shift data and synthetics independent of one another. Covers #159. Implements new tests to cover this functionality, as well as expanded tests to cover `time_shift_s`
- New RecSec Kwargs `obs_zorder` and `syn_zorder` that allow user to set the zorder of the obs and syn when plotting both. Previously these were hardcoded to be the same value so synthetics always plotted on top. Added these kwargs to the docstring documentation.
- Slightly changes look of RecSec by changing column header 'TSHIFT' to 'ΔT' and adds new 'ΔT_SYN' for when a different time shift is reported for synthetics w.r.t …

RecSec feature time_shift_s_syn + update docs
